/* See https://docs.rs/riscv-rt/latest/riscv_rt/ */
MEMORY
{
  FLASH : ORIGIN = 0x80000000, LENGTH = 64K
  RAM : ORIGIN = 0x82000000, LENGTH = 64K
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
