[target.riscv32imac-unknown-none-elf]
runner = "spike --isa RV32IMAFDC"
rustflags = [
  "-C", "link-arg=-Tsrc/linker.ld",
]

[target.riscv64imac-unknown-none-elf]
# runner = "spike -d"
runner = "spike"
rustflags = [
  "-C", "link-arg=-Tsrc/linker.ld",
]

[build]
# target = "riscv32imac-unknown-none-elf"
target = "riscv64imac-unknown-none-elf"
