[target.'cfg(all())']
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]

[target.'cfg(all(target_pointer_width = "32"))']
# linker = "riscv32-unknown-elf-ld"
# linker = "riscv32-elf-ld"

[target.'cfg(all(target_pointer_width = "64"))']
# Would not work because build script would be linked with wrong linker
# linker = "riscv64-unknown-elf-ld"
# linker = "riscv64-elf-ld"

[target.riscv32imac-unknown-none-elf]
runner = "spike --isa RV32IMAFDC"
linker = "riscv32-elf-ld"

[target.riscv64imac-unknown-none-elf]
# runner = "spike -d"
runner = "spike"
linker = "riscv64-elf-ld"

[target.riscv64gc-unknown-none-elf]
# runner = "spike -d"
runner = "spike"
linker = "riscv64-elf-ld"

[build]
# target = "riscv32imac-unknown-none-elf"
target = "riscv64gc-unknown-none-elf"
