/* Also see: https://github.com/riscv-software-src/riscv-tests/blob/51de00886cd28a3cf9b85ee306fb2b5ee5ab550e/benchmarks/common/test.ld */

MEMORY
{
  ALL_MEM : ORIGIN = 0x80000000, LENGTH = 1M
}

REGION_ALIAS("REGION_TEXT", ALL_MEM);
REGION_ALIAS("REGION_RODATA", ALL_MEM);
REGION_ALIAS("REGION_DATA", ALL_MEM);
REGION_ALIAS("REGION_BSS", ALL_MEM);
REGION_ALIAS("REGION_HEAP", ALL_MEM);
REGION_ALIAS("REGION_STACK", ALL_MEM);

/* _stext = 0x80000000; */
